FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY . .

ENV NODE_ENV=production

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push && npx prisma db seed && npm start"]
